# Generated by Django 3.0.8 on 2021-04-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PollsRestAPIApp', '0002_auto_20210411_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'SubCategories'},
        ),
    ]
