# Generated by Django 3.0.8 on 2021-04-27 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PollsRestAPIApp', '0003_auto_20210411_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('polldatetime', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='PollsRestAPIApp.Poll')),
                ('polloptions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polloptions', to='PollsRestAPIApp.PollOption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
